// <auto-generated />
using System;
using LearningSystem.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningSystem.DAL.Migrations
{
    [DbContext(typeof(LearningPlatformContext))]
    [Migration("20240924204139_removeInstrcutorDepartmentUniqueIndex")]
    partial class removeInstrcutorDepartmentUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningSystem.DAL.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            DepartmentId = 1,
                            InstructorId = 1,
                            MinDegree = 50,
                            Name = "Intro to Programming",
                            TotalHours = 40
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            DepartmentId = 1,
                            InstructorId = 1,
                            MinDegree = 60,
                            Name = "Data Structures",
                            TotalHours = 45
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            DepartmentId = 1,
                            InstructorId = 1,
                            MinDegree = 65,
                            Name = "Algorithms",
                            TotalHours = 50
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100,
                            DepartmentId = 2,
                            InstructorId = 2,
                            MinDegree = 55,
                            Name = "Linear Algebra",
                            TotalHours = 40
                        },
                        new
                        {
                            Id = 5,
                            Degree = 100,
                            DepartmentId = 2,
                            InstructorId = 2,
                            MinDegree = 50,
                            Name = "Calculus I",
                            TotalHours = 42
                        },
                        new
                        {
                            Id = 6,
                            Degree = 100,
                            DepartmentId = 3,
                            InstructorId = 3,
                            MinDegree = 60,
                            Name = "Quantum Mechanics",
                            TotalHours = 45
                        },
                        new
                        {
                            Id = 7,
                            Degree = 100,
                            DepartmentId = 4,
                            InstructorId = 4,
                            MinDegree = 65,
                            Name = "Thermodynamics",
                            TotalHours = 50
                        },
                        new
                        {
                            Id = 8,
                            Degree = 100,
                            DepartmentId = 4,
                            InstructorId = 4,
                            MinDegree = 55,
                            Name = "Organic Chemistry",
                            TotalHours = 40
                        },
                        new
                        {
                            Id = 9,
                            Degree = 100,
                            DepartmentId = 6,
                            InstructorId = 6,
                            MinDegree = 50,
                            Name = "Business Strategy",
                            TotalHours = 42
                        },
                        new
                        {
                            Id = 10,
                            Degree = 100,
                            DepartmentId = 6,
                            InstructorId = 6,
                            MinDegree = 60,
                            Name = "Financial Accounting",
                            TotalHours = 45
                        });
                });

            modelBuilder.Entity("LearningSystem.DAL.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GradeLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CourseResult");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Grade = 90.5m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(8962),
                            GradeLetter = "A",
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Grade = 85.0m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9111),
                            GradeLetter = "B",
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Grade = 78.5m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9134),
                            GradeLetter = "C",
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Grade = 88.0m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9153),
                            GradeLetter = "B",
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Grade = 92.5m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9173),
                            GradeLetter = "A",
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            Grade = 80.0m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9191),
                            GradeLetter = "B",
                            TraineeId = 6
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            Grade = 74.5m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9209),
                            GradeLetter = "C",
                            TraineeId = 7
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 8,
                            Grade = 89.0m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9228),
                            GradeLetter = "B",
                            TraineeId = 8
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 9,
                            Grade = 95.0m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9246),
                            GradeLetter = "A",
                            TraineeId = 9
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 10,
                            Grade = 91.5m,
                            GradeDate = new DateTime(2024, 9, 24, 23, 41, 27, 346, DateTimeKind.Local).AddTicks(9266),
                            GradeLetter = "A",
                            TraineeId = 10
                        });
                });

            modelBuilder.Entity("LearningSystem.DAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 2,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 3,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            ManagerId = 4,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 5,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 6,
                            ManagerId = 6,
                            Name = "Business"
                        },
                        new
                        {
                            Id = 7,
                            ManagerId = 7,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 8,
                            ManagerId = 8,
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = 9,
                            ManagerId = 9,
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = 10,
                            ManagerId = 10,
                            Name = "Civil Engineering"
                        });
                });

            modelBuilder.Entity("LearningSystem.DAL.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId1")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            ImageURL = "alice.jpg",
                            Name = "Alice Johnson",
                            Salary = 75000.0,
                            address = "123 Main St"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            ImageURL = "bob.jpg",
                            Name = "Bob Smith",
                            Salary = 80000.0,
                            address = "456 High St"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            ImageURL = "catherine.jpg",
                            Name = "Catherine Williams",
                            Salary = 82000.0,
                            address = "789 Elm St"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            ImageURL = "david.jpg",
                            Name = "David Johnson",
                            Salary = 78000.0,
                            address = "321 Maple Ave"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            ImageURL = "emily.jpg",
                            Name = "Emily Davis",
                            Salary = 76000.0,
                            address = "654 Pine St"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            ImageURL = "frank.jpg",
                            Name = "Frank Miller",
                            Salary = 90000.0,
                            address = "987 Oak St"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 7,
                            ImageURL = "grace.jpg",
                            Name = "Grace Lee",
                            Salary = 85000.0,
                            address = "111 Cedar St"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            ImageURL = "henry.jpg",
                            Name = "Henry Brown",
                            Salary = 88000.0,
                            address = "222 Birch St"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 9,
                            ImageURL = "isabelle.jpg",
                            Name = "Isabelle Wilson",
                            Salary = 86000.0,
                            address = "333 Spruce St"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            ImageURL = "jack.jpg",
                            Name = "Jack Thomas",
                            Salary = 92000.0,
                            address = "444 Ash St"
                        });
                });

            modelBuilder.Entity("LearningSystem.DAL.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            ImageUrl = "john.jpg",
                            Name = "John Doe",
                            address = "101 Apple St"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            ImageUrl = "jane.jpg",
                            Name = "Jane Smith",
                            address = "102 Orange St"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            ImageUrl = "samuel.jpg",
                            Name = "Samuel Green",
                            address = "103 Banana St"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            ImageUrl = "natalie.jpg",
                            Name = "Natalie Brown",
                            address = "104 Peach St"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            ImageUrl = "michael.jpg",
                            Name = "Michael Johnson",
                            address = "105 Grape St"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            ImageUrl = "sophia.jpg",
                            Name = "Sophia Lee",
                            address = "106 Plum St"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 7,
                            ImageUrl = "william.jpg",
                            Name = "William Martinez",
                            address = "107 Pear St"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            ImageUrl = "olivia.jpg",
                            Name = "Olivia Anderson",
                            address = "108 Cherry St"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 9,
                            ImageUrl = "ethan.jpg",
                            Name = "Ethan Scott",
                            address = "109 Kiwi St"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            ImageUrl = "emma.jpg",
                            Name = "Emma Davis",
                            address = "110 Mango St"
                        });
                });

            modelBuilder.Entity("LearningSystem.DAL.Course", b =>
                {
                    b.HasOne("LearningSystem.DAL.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("LearningSystem.DAL.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId");

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("LearningSystem.DAL.CourseResult", b =>
                {
                    b.HasOne("LearningSystem.DAL.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("CourseId");

                    b.HasOne("LearningSystem.DAL.Trainee", "Trainee")
                        .WithMany("CourseResults")
                        .HasForeignKey("TraineeId");

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("LearningSystem.DAL.Instructor", b =>
                {
                    b.HasOne("LearningSystem.DAL.Department", "Department")
                        .WithOne()
                        .HasForeignKey("LearningSystem.DAL.Instructor", "DepartmentId");

                    b.HasOne("LearningSystem.DAL.Department", null)
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId1");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LearningSystem.DAL.Trainee", b =>
                {
                    b.HasOne("LearningSystem.DAL.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LearningSystem.DAL.Course", b =>
                {
                    b.Navigation("CourseResults");
                });

            modelBuilder.Entity("LearningSystem.DAL.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("LearningSystem.DAL.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LearningSystem.DAL.Trainee", b =>
                {
                    b.Navigation("CourseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
